name: 'Find Unused Port'
description: 'Find an unused port on linux and assign it to a GITHUB_ENV var'
author: 'Joshua Balfe <joshuabalfe@googlemail.com>'
inputs:
  var:
    description: 'Name of ENV variable to assign port to'
    required: true
    default: 'PORT'
runs: 
  using: 'composite'
  steps:
    - name: find an unused port and store it as a github env var
      run: |
        read LOWERPORT UPPERPORT < /proc/sys/net/ipv4/ip_local_port_range
        while :
        do
          PORT="`shuf -i $LOWERPORT-$UPPERPORT -n 1`"
          # Check if port is claimed 
          ss -lpn | grep -q ":$PORT " ||
          # Check if a previous run of this action has added this port to $GITHUB_ENV already
          echo $GITHUB_ENV | grep -q "=$PORT" ||
          # If this port isn't claimed and hasn't already been added to the $GITHUB_ENV then add it
          break
        done
        echo "${{ inputs.var }}=$PORT" >> $GITHUB_ENV
      shell: bash
