on: [push]

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Test Find Unused Port
    steps:
      - uses: joshuabalfe/find-unused-port@alpha
        with: 
          var: MY_PORT

      - name: Force failure
        run: |
          echo "MY_PORT=''" >> $GITHUB_ENV

      - name: Verify found port
        run: |
          if [ ${{ env.MY_PORT }} == '' ]
          then 
            echo "No port assigned to github env"
            exit 1
          fi
          echo ${{ env.MY_PORT }}
  