on: [push]

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Test Find Unused Port
    steps:
      - name: Use the find-unused-port action
        uses: joshuabalfe/find-unused-port@v1
        with: 
          var: MY_PORT

      - name: Use the find-unused-port action again
        uses: joshuabalfe/find-unused-port@main
        with: 
          var: MY_OTHER_PORT

      - name: Verify found port was assigned to github env
        run: |
          if [[ "${{ env.MY_PORT }}" == '' ]]
          then 
            echo "No port assigned to github env"
            exit 1
          fi
          echo ${{ env.MY_PORT }}

          if [[ "${{ env.MY_OTHER_PORT }}" == '' ]]
          then 
            echo "No other port assigned to github env"
            exit 1
          fi
          echo ${{ env.MY_OTHER_PORT }}
  