on: [push]

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Test Find Unused Port
    steps:
      - uses: joshuabalfe/find-unused-port@alpha
        with: 
          var: MY_PORT

      - name: Verify found port
        run: |
          if [ ${{ env.MY_PORT }} -eq '' ]
          then 
            exit 1
          fi
          echo ${{ env.MY_PORT }}
        shell: bash


  